### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by reinzor** [pal-robotics/ddynamic_reconfigure_python#2]
Could we get a `Noetic` release :)?

**Comment by reinzor** [comment]
@awesomebytes any updates on this?

**Comment by awesomebytes** [comment]
@v-lopez any chance?

**Comment by v-lopez** [comment]
Yes, let me look into it.

**Comment by v-lopez** [comment]
https://github.com/ros/rosdistro/pull/27196

**Comment by reinzor** [comment]
Can be closed since ros/rosdistro#27196 is merged
